### ISSUE TITLE
Learning Expo/React Native

### ISSUE THREAD

**Issue by ahtae** [hackerDelta/capstone#21]
- [x] Any dev dependencies (i.e. what needs to be installed to start development)
- [x] Expo continuous deployment
- [x] Expo continuous integration
- [x] Useful things to know about React Native

**Comment by courtneycodes95** [comment]
### NOTES

**Incorporating native image selection in app**: https://docs.expo.io/tutorial/image-picker/

**Expo SDK modules** (provide access to device and system functionality): https://docs.expo.io/versions/latest/

**Handling platform differences** (because some React Native components are not available on both OS platforms [or even the browser]): https://docs.expo.io/tutorial/platform-differences/

**Debugging**: https://docs.expo.io/workflow/debugging/

**Expo Continuous Integration/Continuous Deployment**: https://docs.expo.io/guides/setting-up-continuous-integration/

**Component collections** (pre-styled components):
* React Native Elements - https://github.com/react-native-elements/react-native-elements
* NativeBase - https://github.com/GeekyAnts/NativeBase

**Quick info about React Native and its components**: http://www.reactnativeexpress.com/

**React Native documentation**: https://reactnative.dev/docs/getting-started.html
